#ifndef PHONE_BUDDY_H
#define PHONE_BUDDY_H

/* Automatically generated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque engine handle.
 */
typedef struct PbEngine PbEngine;

/**
 * Opaque long-lived routing runtime handle.
 */
typedef struct PbRuntime PbRuntime;

/**
 * One-shot `generate_text` completion callback.
 *
 * `envelope_json` is a versioned JSON object valid only for the duration of
 * the call. Copy it if you keep it. Invoked from a background worker thread.
 * Do not reuse chat session event callbacks for this.
 */
typedef void (*PbOperationCallback)(const char *envelope_json, void *user_data);

/**
 * Streaming event callback.
 *
 * `event_json` is a UTF-8 JSON string describing one [`AgentEvent`].
 * It is valid only for the duration of the call; copy it if you keep it.
 * The callback may be invoked from a background engine thread.
 */
typedef void (*PbEventCallback)(const char *event_json, void *user_data);

/**
 * Host LLM request callback.
 *
 * Fired when the engine needs a completion. `request_id` and `request_json`
 * are valid only for the duration of the call. Respond with
 * [`pb_engine_llm_push_chunk`] / [`pb_engine_llm_finish`] /
 * [`pb_engine_llm_fail`].
 */
typedef void (*PbLlmRequestCallback)(const char *request_id,
                                     const char *request_json,
                                     void *user_data);

/**
 * Host tool request callback.
 *
 * Fired when a host-registered tool must run. Respond with
 * [`pb_engine_host_tool_result`].
 */
typedef void (*PbHostToolCallback)(const char *call_id,
                                   const char *name,
                                   const char *arguments_json,
                                   void *user_data);

/**
 * Host system WebView fetch callback.
 *
 * Fired when `web_search` wants DuckDuckGo Lite loaded in WKWebView /
 * Android WebView. `request_json` is a [`phone_buddy::tools::WebViewFetchRequest`].
 * Respond with [`pb_engine_webview_result`]. Desktop / C hosts should leave
 * this unset so search skips scraping and uses the LLM API.
 */
typedef void (*PbWebViewFetchCallback)(const char *call_id,
                                       const char *request_json,
                                       void *user_data);

/**
 * Native logging callback.
 * `level`: 1 = ERROR, 2 = WARN, 3 = INFO, 4 = DEBUG, 5 = TRACE.
 * `target`: Logger target / module name (C-string).
 * `message`: Formatted log text (C-string).
 */
typedef void (*PbLogCallback)(int32_t level, const char *target, const char *message);

/**
 * Library version string. Do not free.
 */
const char *pb_version(void);

/**
 * Create an engine from a JSON configuration.
 *
 * `config_json` must match [`phone_buddy::config::EngineConfig`].
 * On success returns a handle and writes null to `err_out`; on failure
 * returns null and writes an error message to `err_out` (caller frees with
 * [`pb_string_free`]).
 *
 * # Safety
 * `config_json` must be a valid C string. `err_out` may be null.
 */
struct PbEngine *pb_engine_new(const char *config_json, char **err_out);

/**
 * Free an engine handle.
 *
 * # Safety
 * `engine` must be a handle returned by [`pb_engine_new`], or null.
 */
void pb_engine_free(struct PbEngine *engine);

/**
 * Create a long-lived routing runtime from a JSON [`LlmRoutingConfig`].
 *
 * # Safety
 * `routing_config_json` and `root_dir` must be valid C strings. `err_out` may be null.
 */
struct PbRuntime *pb_runtime_new(const char *routing_config_json,
                                 const char *root_dir,
                                 char **err_out);

/**
 * Replace routing on an existing runtime. In-flight operations may finish
 * on a previously captured snapshot.
 *
 * Returns 0 on success.
 *
 * # Safety
 * `runtime` must be a handle from [`pb_runtime_new`]. `routing_config_json` must be a valid C string.
 */
int32_t pb_runtime_update_routing(struct PbRuntime *runtime,
                                  const char *routing_config_json,
                                  char **err_out);

/**
 * Create an engine bound to `runtime`. `main_pool_id` defaults to `"main"` when null.
 *
 * # Safety
 * `runtime` must outlive the returned engine. `agent_config_json` must be valid.
 */
struct PbEngine *pb_engine_new_with_runtime(struct PbRuntime *runtime,
                                            const char *agent_config_json,
                                            const char *main_pool_id,
                                            char **err_out);

/**
 * Start tool-free one-shot generation. Returns `operation_id` immediately.
 * Completion is delivered through `callback` as a versioned JSON envelope.
 *
 * # Safety
 * `runtime` and `request_json` must be valid. `callback` may be null (result discarded).
 * The callback and `user_data` must remain valid until the envelope is delivered.
 */
char *pb_runtime_generate_text_async(struct PbRuntime *runtime,
                                     const char *request_json,
                                     PbOperationCallback callback,
                                     void *user_data,
                                     char **err_out);

/**
 * Cancel a one-shot operation started by [`pb_runtime_generate_text_async`].
 *
 * # Safety
 * `runtime` and `operation_id` may be null (no-op).
 */
void pb_runtime_cancel_operation(struct PbRuntime *runtime, const char *operation_id);

/**
 * Cancel outstanding one-shot operations without freeing the shared runtime.
 * Routing and provider health remain available for subsequent operations.
 *
 * # Safety
 * `runtime` must be a live handle returned by [`pb_runtime_new`], or null.
 */
void pb_runtime_cancel_all(struct PbRuntime *runtime);

/**
 * Free a runtime handle. Outstanding one-shot operations are cancelled.
 *
 * # Safety
 * `runtime` must be a handle returned by [`pb_runtime_new`], or null.
 */
void pb_runtime_free(struct PbRuntime *runtime);

/**
 * Run one chat turn to completion (blocking). Call from a background
 * thread; streaming events are delivered via `callback` as they happen.
 *
 * Returns a JSON object `{ "final_text", "turns_used", "usage", "plan" }`
 * on success, or null on error (with `err_out` set). Caller frees the
 * result with [`pb_string_free`].
 *
 * # Safety
 * All pointers must be valid. `callback` may be null (events discarded).
 */
char *pb_engine_chat(struct PbEngine *engine,
                     const char *session_id,
                     const char *user_input,
                     PbEventCallback callback,
                     void *user_data,
                     char **err_out);

/**
 * Run one versioned structured user turn (`schema_version: 1`).
 * Invalid JSON, unsupported schema versions, missing attachments, or invalid
 * content parts are returned through `err_out`. There is no text fallback.
 *
 * # Safety
 * All pointers must be valid. `callback` may be null (events discarded).
 */
char *pb_engine_chat_v2(struct PbEngine *engine,
                        const char *session_id,
                        const char *turn_json,
                        PbEventCallback callback,
                        void *user_data,
                        char **err_out);

/**
 * List sessions as a JSON array of metadata objects. Caller frees.
 *
 * # Safety
 * `engine` must be valid.
 */
char *pb_engine_list_sessions(struct PbEngine *engine, char **err_out);

/**
 * Get full session JSON (including all messages and reasoning) for a given session ID.
 *
 * Returns a JSON string matching [`phone_buddy::session::StoredSession`] on success,
 * or null if the session does not exist (with `err_out` set to null), or null on
 * error (with `err_out` set to an error message). Caller frees the returned JSON string
 * with [`pb_string_free`].
 *
 * # Safety
 * `engine` and `session_id` must be valid. `err_out` may be null.
 */
char *pb_engine_get_session(struct PbEngine *engine, const char *session_id, char **err_out);

/**
 * Delete a session. Returns 0 on success, non-zero on error.
 *
 * # Safety
 * `engine` and `session_id` must be valid.
 */
int32_t pb_engine_delete_session(struct PbEngine *engine, const char *session_id);

/**
 * Cancel an in-flight turn for a session.
 *
 * # Safety
 * `engine` and `session_id` must be valid.
 */
void pb_engine_cancel(struct PbEngine *engine, const char *session_id);

/**
 * Register host LLM + host-tool request callbacks.
 *
 * Pass null callbacks to clear. `user_data` is passed through to both
 * callbacks and must remain valid until the engine is freed or callbacks
 * are cleared.
 *
 * # Safety
 * Callbacks may be invoked from engine worker threads.
 */
void pb_engine_set_host_callbacks(struct PbEngine *engine,
                                  PbLlmRequestCallback llm_cb,
                                  PbHostToolCallback tool_cb,
                                  void *user_data);

/**
 * Push one OpenAI-compatible chat-completion chunk for a host LLM request.
 *
 * Returns 0 on success, non-zero on error (`err_out` set when provided).
 */
int32_t pb_engine_llm_push_chunk(struct PbEngine *engine,
                                 const char *request_id,
                                 const char *chunk_json,
                                 char **err_out);

/**
 * Finish a host LLM stream successfully.
 */
int32_t pb_engine_llm_finish(struct PbEngine *engine, const char *request_id, char **err_out);

/**
 * Fail a host LLM stream.
 */
int32_t pb_engine_llm_fail(struct PbEngine *engine,
                           const char *request_id,
                           const char *error_msg,
                           char **err_out);

/**
 * Register host tools from an OpenAI tools JSON array.
 *
 * Returns 0 on success.
 */
int32_t pb_engine_set_host_tools(struct PbEngine *engine, const char *tools_json, char **err_out);

/**
 * Complete a host tool call. `ok` is non-zero for success.
 */
int32_t pb_engine_host_tool_result(struct PbEngine *engine,
                                   const char *call_id,
                                   int32_t ok,
                                   const char *output,
                                   char **err_out);

/**
 * Register a host system WebView fetch callback.
 *
 * iOS / Android wrappers should set this to drive a hidden WKWebView or
 * Android WebView. Pass a null callback to clear (desktop / C hosts).
 * `user_data` must remain valid until the engine is freed or the callback
 * is cleared.
 *
 * # Safety
 * The callback may be invoked from an engine worker thread. The host must
 * hop to the UI thread before creating or touching a WebView.
 */
void pb_engine_set_webview_callback(struct PbEngine *engine,
                                    PbWebViewFetchCallback callback,
                                    void *user_data);

/**
 * Complete a host WebView fetch. `ok` is non-zero for success; `output` is
 * the document HTML on success or an error message on failure.
 *
 * # Safety
 * `engine` and `call_id` must be valid. `output` may be null (treated as empty).
 */
int32_t pb_engine_webview_result(struct PbEngine *engine,
                                 const char *call_id,
                                 int32_t ok,
                                 const char *output,
                                 char **err_out);

/**
 * Set or clear the system prompt extra text (Pal persona).
 *
 * Pass null `extra` to clear.
 */
void pb_engine_set_system_prompt_extra(struct PbEngine *engine, const char *extra);

/**
 * Set the system-prompt identity (`You are {name}…`).
 *
 * Pass null or empty `name` to reset to the default (`PhoneBuddy`).
 */
void pb_engine_set_agent_name(struct PbEngine *engine, const char *name);

/**
 * Free a string returned by this library.
 *
 * # Safety
 * `ptr` must be a string returned by this library, or null.
 */
void pb_string_free(char *ptr);

/**
 * Initialize native logging for debugging.
 * `min_level`: 1=ERROR, 2=WARN, 3=INFO, 4=DEBUG, 5=TRACE, <=0=disabled.
 * On Android, automatically attaches logcat layer alongside the host callback.
 * In release builds (`release_max_level_off`), tracing macros are stripped at compile-time.
 * Ranked server-list dumps use [`phone_buddy::diag`] so they still reach the
 * host callback in those release binaries.
 */
void pb_init_logging(PbLogCallback callback, int32_t min_level);

#endif  /* PHONE_BUDDY_H */
